### ISSUE TITLE
physical problem with the animation

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar-art#2]
I don't want to be a prick or anything..  : D

But I believe that "physically" the direction of the animation of the spinning logo is in the wrong direction:
quasar-art/src/quasar-logo-animated.svg

If you look at a quasar, you see how the light/gas gets swallowed as it turns.
![eso1229a](https://user-images.githubusercontent.com/3253920/35479455-65f8532a-043b-11e8-9404-93d27aba898d.jpg)

And in the spinning logo it turns into the direction of the light that's furthest away first...

Sorry for the bad explanation.

**Comment by zuck** [comment]
So, do you mean it has to rotate counter-clockwise? 😄

**Comment by mesqueeb** [comment]
Yeah!!

**Comment by nothingismagick** [comment]
you know that is so funny because i was just going to file exactly the same issue.

**Comment by nothingismagick** [comment]
also - it looks more like a circular saw than a toilet. :poop:
